config/routes.rb
Rails.application.routes.draw do      
  root :to => 'pages#home' 
  resources:users, :only => [:new, :create, :index]
  resources:stocks, :only => [:index, :show, :create, :update, :destroy]
  resources:watchlists

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_and_belongs_to_many :watchlists
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password      
    validates :email, :presence => true, :uniqueness => true
    has_many :watchlists
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
    belongs_to :user, :optional => true 
    has_and_belongs_to_many :stocks    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present? # Log out non-existent users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_for_login 
  
  def home    
    stocks_list = ['ADBE', 'NVDA', 'NKE', 'SHOP','GOOG', 'MSFT', 'AMZN', 'TSLA', 'AAPL', 'T', 'V', 'PEP', 'IBM', 'CRM', 'HUBS', 'PFE','SBUX','MCD']
   
    @stocks_db = Stock.all
    @stocks_db_symbols = []
    @stocks_db.each do |stock|
      @stocks_db_symbols << stock.symbol 
    end

    stocks_list.each do |symbol|
      if @stocks_db_symbols.exclude?(symbol)
        @stock = Stock.create :symbol => symbol    
      end
    end 

    @featured_stocks =  Stock.where(symbol: stocks_list) 
    
  end 
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  require 'net/http'
  require 'uri'
  before_action :check_for_login

  def index
    @stocks = Stock.all
  end

  def show
    @watchlists = @current_user.watchlists  
    @stock = Stock.find params[:id]
  end

  def create
    input_symbol = params[:symbol].upcase    
    query = BasicYahooFinance::Query.new
    stock_data = query.quotes(input_symbol)
    if stock_data.keys.length == 1      
      stock = Stock.find_by :symbol => input_symbol
      if stock.present?
        redirect_to stock
      else
        stock = Stock.create :symbol => input_symbol
        redirect_to stock
      end
    else
      redirect_to stocks_path
    end   
  end

  def update  # Updates the stocks in the watchlist
    stock = Stock.find_by :symbol => params[:stock][:symbol] 
    watchlist = Watchlist.find params[:stock][:watchlist_ids]
    stocks_arr = []
    watchlist.stocks.each do |w|
      stocks_arr << w.symbol
    end
    if stocks_arr.exclude?(stock.symbol) 
      watchlist.stocks << stock    
    end    
    redirect_to stock    
  end

  def destroy  # Deletes the stocks in the watchlist
    watchlist = Watchlist.find params[:watchlist][:id]
    stock_id = params[:id].to_i
    
    watchlist.stocks.each do |s|
      if (s.id == stock_id)
      s.destroy
      s.save
      end
    end
    watchlist.save   
    redirect_to watchlist
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new  
    end
  end

  private
  def user_params    
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :check_for_login
  def index
    @watchlists = @current_user.watchlists
  end

  def new
    @watchlist = Watchlist.new
  end

  def create  
    watchlist = Watchlist.create watchlist_params   
    @current_user.watchlists << watchlist # Give the new watchlist to the user
    redirect_to watchlist
  end

  def edit   
    @watchlist = Watchlist.find params[:id] 
  end

  def update
    watchlist = Watchlist.find params[:id]
    watchlist.update watchlist_params
    redirect_to watchlist
  end

  def show
    @watchlist = Watchlist.find params[:id]
  end

  def destroy
    watchlist = Watchlist.find params[:id]
    watchlist.destroy
    redirect_to watchlists_path
  end

  private
  def watchlist_params
    params.require(:watchlist).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">      
      <%= link_to "Stockr", root_path, :class => 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if @current_user.present? %>
            <li><%= link_to "Home", root_path, :class => 'nav-link' %></li>
            <% if @current_user.admin? %>
              <li><%= link_to "Users", users_path, :class => 'nav-link' %></li>          
            <% end%>
            <li><%= link_to "Markets", stocks_path, :class => 'nav-link' %></li>   
            <li><%= link_to "Watchlist", watchlists_path, :class => 'nav-link' %></li>   
            <%= form_tag stocks_path, :class => 'd-flex' do %>        
              <%= text_field_tag :symbol, "", :class => 'form-control me-2', type:"search", placeholder:"AMZN" %>
              <%= submit_tag "Search", :class => 'btn btn-outline-success'%>              
            <% end %> 
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
              <%= link_to "Sign out", login_path, :method => 'delete', :class => 'btn navbar-btn btn-danger', role:"button" %>
          </li>     
        </ul>   
        <% else %>
          <li><%= link_to "Sign in", login_path, :class => 'nav-link' %></li>
          <li><%= link_to "Sign up", new_user_path, :class => 'nav-link' %></li> 
        <% end %>       
      </div>          
    </nav>
    <div class="container">
       <%= yield %>
    </div>   
  </body>
</html>

app/views/pages/home.html.erb
<% require 'news-api'%>

<% if @current_user.present?  %>
    <h2>Welcome <%= @current_user.first_name %>, </h2>

    <span>Trending stocks</span>
    <%= link_to "View more", stocks_path, :class => 'btn btn-outline-dark view-all' %>

    <% query = BasicYahooFinance::Query.new  %>    
     
    <div class="stock-wrapper">
        <% @featured_stocks.each do |stock|%>
        <% info = query.quotes(stock.symbol)%>      
        <div class="stock-card">
            <div class="top">
                <div class="card-top">                                       
                    <%= link_to image_tag(("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png"), :class => 'stock-icon-card'), stock %>  
                </div>                
                <div class="card-top">
                    <p class="symbol-text-card"> <%= stock.symbol %></p>
                    <p class="name-card"> <%= info[stock.symbol]['displayName'] %></p>
                </div>            
            </div>            
            <div class="card-bottom">
                <span><%= number_to_currency info[stock.symbol]['regularMarketPrice'] %></span>   
                <% change_percent = info[stock.symbol]['regularMarketChangePercent'] %>
                <% if change_percent > 0 %>
                    <span class="green"><%= number_to_percentage change_percent %></span>
                <% else %>
                    <span class="red"><%= number_to_percentage change_percent %></span>
                <% end %>            
            </div>      
        </div>
        <% end %>  
    </div>

    <p class="second-level-header">Financial news</p>
    <div class="news-wrapper-home">        
        <% news_info =  News.new(ENV["NEWS_API_KEY"]) %>
        <% all_news = news_info.get_top_headlines(category: "business", language: "en")%>
        <% news = all_news.first(12) %>
        <% news.each do |n| %>
        <div class="news-card-home" >
            <h5 class="card-title news-title-home"> <%= link_to truncate(n.title, :length => 50), n.url, target: '_blank' %> </h5>
            <%= image_tag(n.urlToImage || "https://www.newsanyway.com/wp-content/uploads/2022/03/In-the-news-4-10-March-2022.jpg", :class => 'card-img-top') %>
            <div class="card-body">
                <p class="card-title news-desc-home"> <%= truncate(n.description, :length => 100) %> </p>
            </div>
        </div> 
        <% end %>
    </div>    
<% end  %>

app/views/session/new.html.erb
<%= form_tag login_path, {class: 'col-lg-6 offset-lg-3'} do %>
    <h2>Sign in</h2>
    <div class="mb-3 col-6">
    <%= label_tag :email, nil, :class => 'form-label' %>
    <%= email_field_tag :email, nil, :class => 'form-control' %>
    </div>
    <div class="mb-3 col-6">
    <%= label_tag :password, nil, :class => 'form-label' %>
    <%= password_field_tag :password, nil, :class => 'form-control' %>
    </div>
    <%= submit_tag "Sign in", :class => 'btn authentication-btn' %>

<% end%>

app/views/stocks/index.html.erb
<h2>Market insights</h2>

<% def remote_file_exists?(url) %>
    <% url = URI.parse(url) %>
    <% http = Net::HTTP.new(url.host, url.port) %>
    <% http.use_ssl = (url.scheme == "https") %>
    <% http.start do |http| %>
        <% return http.head(url.request_uri)['Content-Type'].start_with? 'image' %>
    <% end %>
<% end %>

<% query = BasicYahooFinance::Query.new  %>    

<p class="second-level-header">Top Gainers</p>
   
<div class="stock-wrapper">
    <% @stocks.each do |stock|%>
        <% info = query.quotes(stock.symbol)%>   
        <% change_percent = info[stock.symbol]['regularMarketChangePercent'] %>     
        <% if change_percent %>
            <% if change_percent > 2 %>
                <div class="stock-card">
                    <div class="top">
                        <div class="card-top">    
                            <% if remote_file_exists?("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png") %>
                                <%= link_to image_tag(("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png"), :class => 'stock-icon-card'), stock %>  
                            <% else %>
                                <%= link_to image_tag(("https://i.imgur.com/WfkBi7F.jpg"), :class => 'stock-icon-card'), stock %>  
                            <% end %>
                        </div>                
                        <div class="card-top">
                            <p class="symbol-text-card"> <%= stock.symbol %></p>
                            <p class="name-card"> <%= info[stock.symbol]['displayName'] %></p>
                        </div>            
                    </div>            
                    <div class="card-bottom">
                        <span><%= number_to_currency info[stock.symbol]['regularMarketPrice'] %></span>   
                        <span class="green"><%= number_to_percentage change_percent %></span>  
                    </div>      
                </div>
            <% end %>       
        <% end %>
    <% end %>  
</div>
 
 <p class="second-level-header">Top Losers</p>
   
<div class="stock-wrapper">
    <% @stocks.each do |stock|%>
    <% info = query.quotes(stock.symbol)%>   
    <% change_percent = info[stock.symbol]['regularMarketChangePercent'] %>     
        <% if change_percent < -2 %>
            <div class="stock-card">
                <div class="top">
                    <div class="card-top">                                       
                        <% if remote_file_exists?("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png") %>
                            <%= link_to image_tag(("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png"), :class => 'stock-icon-card'), stock %>  
                        <% else %>
                            <%= link_to image_tag(("https://i.imgur.com/WfkBi7F.jpg"), :class => 'stock-icon-card'), stock %>  
                        <% end %>
                    </div>                
                    <div class="card-top">
                        <p class="symbol-text-card"> <%= stock.symbol %></p>
                        <p class="name-card"> <%= info[stock.symbol]['displayName'] %></p>
                    </div>            
                </div>            
                <div class="card-bottom">
                    <span><%= number_to_currency info[stock.symbol]['regularMarketPrice'] %></span>  
                    <span class="red"><%= number_to_percentage change_percent %></span>       
                </div>      
            </div>
        <% end %>        
    <% end %>  
</div>


<p class="second-level-header">Financial news</p>
<div class="news-wrapper-home">    
    <% news_info =  News.new(ENV["NEWS_API_KEY"]) %>
    <% all_news = news_info.get_top_headlines(category: "business", language: "en")%>
    <% news = all_news.sample(12) %>    
    <% news.each do |n| %>
        <div class="news-card-home" >
            <h5 class="card-title news-title-home"> <%= link_to truncate(n.title, :length => 50), n.url, target: '_blank' %> </h5>
            <%= image_tag(n.urlToImage || "https://www.newsanyway.com/wp-content/uploads/2022/03/In-the-news-4-10-March-2022.jpg", :class => 'card-img-top') %>
            <div class="card-body">
                <p class="card-title news-desc-home"> <%= truncate(n.description, :length => 100) %> </p>
            </div>
        </div> 
    <% end %>
</div>

app/views/stocks/show.html.erb
<% def remote_file_exists?(url) %>
    <% url = URI.parse(url) %>
    <% http = Net::HTTP.new(url.host, url.port) %>
    <% http.use_ssl = (url.scheme == "https") %>
    <% http.start do |http| %>
        <% return http.head(url.request_uri)['Content-Type'].start_with? 'image' %>
    <% end %>
<% end %>

<% query = BasicYahooFinance::Query.new  %>   
<% info = query.quotes(@stock.symbol)%>      

<div class="container stock-show-container">
    <div class="stock-card-show">
        <div class="top">
            <div class="card-top">      
                <% if remote_file_exists?("https://etoro-cdn.etorostatic.com/market-avatars/#{@stock.symbol.downcase}/150x150.png") %>
                    <%= image_tag(("https://etoro-cdn.etorostatic.com/market-avatars/#{@stock.symbol.downcase}/150x150.png"), :class => 'stock-show-icon') %>  
                <% else %>
                    <%= image_tag(("https://i.imgur.com/WfkBi7F.jpg"), :class => 'stock-show-icon')%>  
                <% end %>
            </div> 
            <div class="card-top">
                <p class="stock-symbol-show"> <%= @stock.symbol %>  </p>                 
                <p class="stock-name-show"> <%= info[@stock.symbol]['shortName'] %> </p>
                <p class="stock-price-show"><%= number_to_currency info[@stock.symbol]['regularMarketPrice'] %></p>    
            </div> 
        </div>   
    </div>
    
    <div class="stock-info-show">
        <p class="stock-info-text">Change</p>
        <p class="stock-info-text stock-info-value"> <%= number_to_currency info[@stock.symbol]['regularMarketChange'] %> </p>
        <p class="stock-info-text">Change %</p>
        <p class="stock-info-text stock-info-value"> <%= number_to_percentage info[@stock.symbol]['regularMarketChangePercent'] %> </p>
        <p class="stock-info-text"> High </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_currency info[@stock.symbol]['regularMarketDayHigh'] %> </p>
        <p class="stock-info-text"> Low </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_currency info[@stock.symbol]['regularMarketDayLow'] %> </p>
        <p class="stock-info-text"> 52W H </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_currency info[@stock.symbol]['fiftyTwoWeekHigh'] %> </p>
        <p class="stock-info-text"> 52W L </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_currency info[@stock.symbol]['fiftyTwoWeekLow'] %> </p>
        <p class="stock-info-text"> Mkt Cap </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_human info[@stock.symbol]['marketCap'] %> </p>
        <p class="stock-info-text"> P/E Ratio </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_human info[@stock.symbol]['forwardPE'] %> </p>
        <p class="stock-info-text"> EPS </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_human info[@stock.symbol]['epsCurrentYear'] %> </p>    
        <p class="stock-info-text"> Div. Yield </p>
        <p class="stock-info-text stock-info-value"> <%= number_to_percentage info[@stock.symbol]['trailingAnnualDividendYield'] %> </p>
    </div>
        
    <div class="stock-watchlist">
        <%=form_for @stock do |f|%>
            <%=f.select "watchlist_ids", @watchlists.map{|w|[w.name, w.id]}%>
            <%=f.hidden_field :symbol, :value=>@stock["symbol"] %>       
            <%=f.hidden_field :user_id, :value=>@current_user.id%>    
            <%=f.submit "Add to watchlist", :class => 'add-to-watchlist-btn' %>
        <%end%>
    </div>       
</div>



                                                 
        
                        
                        

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
    <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, html: {class: "col-lg-6 offset-lg-3"} do |f| %>
    <h2>Sign up</h2>
    <div class="mb-3 col-6">
        <%= f.label :first_name, :class => 'form-label' %>
        <%= f.text_field :first_name, :required => true, :class => 'form-control' %>
    </div>
    <div class="mb-3 col-6">
        <%= f.label :last_name, :class => 'form-label' %>
        <%= f.text_field :last_name, :required => true, :class => 'form-control' %>
    </div>
    <div class="mb-3 col-6">
        <%= f.label :email, :class => 'form-label' %>
        <%= f.email_field :email, :required => true, :class => 'form-control' %>
    </div>
    <div class="mb-3 col-6">
        <%= f.label :password, :class => 'form-label' %>    
        <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <div class="mb-3 col-6">
        <%= f.label :password_confirmation, "Confirm Password", :class => 'form-label' %>
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
    <%= f.submit "Sign up!", :class => 'btn authentication-btn' %>
<% end %>

<% if @user.errors.any? %>
    <ol>
            <% @user.errors.full_messages.each do |msg|  %>
                <li><%= msg %></li>
            <% end %>
    </ol>
<% end %>

app/views/watchlists/_form.html.erb
<%= form_for @watchlist do |f| %>
    <%= f.label :name %>   
    <%= f.text_field :name, :required => true %> 
    <%= f.submit %>
<% end %>

app/views/watchlists/edit.html.erb
<h2>Edit Watchlist</h2>

<%= render :partial => 'form' %>

app/views/watchlists/index.html.erb
<% def remote_file_exists?(url) %>
    <% url = URI.parse(url) %>
    <% http = Net::HTTP.new(url.host, url.port) %>
    <% http.use_ssl = (url.scheme == "https") %>
    <% http.start do |http| %>
        <% return http.head(url.request_uri)['Content-Type'].start_with? 'image' %>
    <% end %>
<% end %>


<div class="watchlist-display-div">
    <span class="watchlist-index-header" >My watchlists</span>
    <%= link_to "+", new_watchlist_path, :class => 'btn btn-outline-primary add-watclist-btn'%>
    <div class="watchlist-index-wrapper">   
        <% @watchlists.each do |watchlist| %>
            <div class="watchlist-card">
                <p class="watchlist-name-index"><%= link_to watchlist.name, watchlist, :class => "watchlist-name-index" %></p>            
                <% watchlist.stocks.each do |stock| %>                      
                    <% if remote_file_exists?("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png") %>
                        <%= image_tag(("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png"), :class => 'watchlist-index-stock-icon') %>  
                    <% else %>
                        <%= image_tag(("https://i.imgur.com/WfkBi7F.jpg"), :class => 'watchlist-index-stock-icon')%>  
                    <% end %> 
                <% end %>
            </div> 
        <% end %>  
    </div> 
</div>

app/views/watchlists/new.html.erb
<h2>New Watchlist</h2>

<%= render :partial => 'form' %>

app/views/watchlists/show.html.erb
<% def remote_file_exists?(url) %>
    <% url = URI.parse(url) %>
    <% http = Net::HTTP.new(url.host, url.port) %>
    <% http.use_ssl = (url.scheme == "https") %>
    <% http.start do |http| %>
        <% return http.head(url.request_uri)['Content-Type'].start_with? 'image' %>
    <% end %>
<% end %>

<div class="watchlist-display-div">
    <span class="watchlist-index-header"><%= @watchlist.name %></span>

    <%= link_to 'Update', edit_watchlist_path(@watchlist), :class => "btn watchlist-control-btn control-update-btn" %>
    <%= link_to 'Delete', @watchlist, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => "btn control-delete-btn" %>

    <div class="row stock-show-watchlist watchlist-stocks-header">
        <div class="watchlist-headers col hidden">Icon</div>
        <div class="watchlist-headers col">Ticker</div>
        <div class="watchlist-headers col-2">Name</div>
        <div class="watchlist-headers col">Change</div>
        <div class="watchlist-headers col">Change %</div>        
        <div class="watchlist-headers col">52W L</div>
        <div class="watchlist-headers col">52W H</div>
        <div class="watchlist-headers col">Buy</div>
        <div class="watchlist-headers col hidden">Delete</div>
    </div>

    <% query = BasicYahooFinance::Query.new  %>  
   
    <% @watchlist.stocks.each do |stock| %>
        <div class="row stock-show-watchlist">
            <% info = query.quotes(stock.symbol)%>
            <div class="col">
                <% if remote_file_exists?("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png") %>
                    <%= image_tag(("https://etoro-cdn.etorostatic.com/market-avatars/#{stock.symbol.downcase}/150x150.png"), :class => 'watchlist-index-stock-icon') %>  
                <% else %>
                    <%= image_tag(("https://i.imgur.com/WfkBi7F.jpg"), :class => 'watchlist-index-stock-icon')%>  
                <% end %> 
            </div>
            <div class="col">
                <p class="stock-info-in-watchlist"> <%= stock.symbol %>
            </div>
            <div class="col-2">
                <p class="stock-info-in-watchlist"><%= info[stock.symbol]['displayName'] %></p>
            </div>
            <div class="col"> 
                <% change = info[stock.symbol]['regularMarketChange'] %>
                <% if change > 0 %>
                    <p class="stock-info-in-watchlist green"><%= number_to_currency change %></p>
                <% else %>
                    <p class="stock-info-in-watchlist red"><%= number_to_currency change %></p>
                <% end %>               
            </div>
            <div class="col">
                <% change_percent = info[stock.symbol]['regularMarketChangePercent'] %>
                <% if change_percent > 0 %>
                    <p class="stock-info-in-watchlist green"><%= number_to_percentage change_percent %></p>
                <% else %>
                    <p class="stock-info-in-watchlist red"><%= number_to_percentage change_percent %></p>
                <% end %> 
            </div>
            <div class="col">
                <p class="stock-info-in-watchlist"><%= number_to_currency info[stock.symbol]['fiftyTwoWeekLow'] %> </p>
            </div>
            <div class="col">
                <p class="stock-info-in-watchlist"><%= number_to_currency info[stock.symbol]['fiftyTwoWeekHigh'] %> </p>
            </div>
            <div class="col">
                <p class="stock-info-in-watchlist"><%= number_to_currency info[stock.symbol]['regularMarketPrice'] %> </p>
            </div>
            <div class="col">                
                <%=form_for @watchlist, method: :delete, url:"/stocks/#{stock.id}" do |f|%>        
                    <%=f.hidden_field :symbol, :value=>stock["symbol"] %>  
                    <%=f.hidden_field :id, :value=>@watchlist.id%>      
                    <%=f.hidden_field :user_id, :value=>@current_user.id%>    
                    <%=f.submit "X", :class => "stock-del-watchlist-btn btn btn-outline-danger" %>
                <%end%>  
            </div>
        </div>
    <% end %>      
</div>